export const FETCH_GITHUB_USER_REQUEST = 'FETCH_GITHUB_USER_REQUEST'
export const FETCH_GITHUB_USER = 'FETCH_GITHUB_USER'
export const FETCH_GITHUB_USER_FAIL = 'FETCH_GITHUB_USER_FAIL'

export const FETCH_REPOS = 'FETCH_REPOS'
export const FETCH_REPOS_FAIL = 'FETCH_REPOS_FAIL'

export const FETCH_ISSUES = 'FETCH_ISSUES'
export const FETCH_ISSUES_FAIL = 'FETCH_ISSUES_FAIL'

export const CREATE_ISSUE = 'CREATE_ISSUE'
export const CREATE_ISSUE_FAIL = 'CREATE_ISSUE_FAIL'
